### ISSUE TITLE
issue with AntiRaid.py

### ISSUE THREAD

**Issue by Note2Self** [Quintenvw/Q-cogs#1]
Hey there seems to be an issue with AntiRaid.py cog. initially it worked for a time then it started throwing this error 

`  File "C:\Users\Tom\Documents\bot\cogs\AntiRaid.py", line 19, in on_member_join
    last_reset = datetime.strptime(self.settings[server.id]["time_since_last_reset"], "%Y-%m-%d %H:%M:%S.%f")
TypeError: strptime() argument 1 must be str, not None`

not sure whats causing this but it seems to be on line 19:

`last_reset = datetime.strptime(self.settings[server.id]["time_since_last_reset"], "%Y-%m-%d %H:%M:%S.%f")`

**Comment by sean-james** [comment]
Did you add datetime to your requirements.txt?

**Comment by Note2Self** [comment]
That fixed the issue thank you 💯
